@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package konsola5.hephaestusplus.modifiers.dynamic;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;