@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package konsola5.hephaestusplus.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;